name: dlsud_go
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.15.2
  mapbox_maps_flutter: ^2.12.0
  geolocator: ^14.0.2
  http: ^0.13.6
  flutter_dotenv: ^6.0.0
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.8
  dialog_flowtter: ^0.3.3
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  mobile_scanner: ^7.1.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  firebase_storage: ^12.4.10
  cached_network_image: ^3.3.1
  image_picker: ^1.2.1
  panorama_viewer: ^2.0.7
  file_picker: ^10.3.7
  supabase_flutter: ^2.3.4
  webview_flutter: ^4.13.0
  image: ^4.0.17
  firebase_database: ^11.3.10
  google_mlkit_translation: ^0.13.0
  desktop_drop: ^0.7.0
  easy_localization: ^3.0.8
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LOGO.png"

flutter:
  generate: true
  uses-material-design: true

  # Modern font families for enhanced typography
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700

  assets:
    - .env
    - assets/dialogflow_key.json
    - assets/images/
    - assets/translations/
    # Add font assets
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-ExtraBold.ttf
    - assets/fonts/Montserrat-SemiBold.ttf
    - assets/fonts/RobotoSlab-Bold.ttf